//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v3"

func main() {
	// Mode returns the most frequent numeric value or values in a slice.
	// If multiple values tie for highest frequency, all are returned
	// in first-seen order.

	// Example: integers - single mode
	collection.Dump(collection.Mode([]int{1, 2, 2, 3}))
	// #[]int [
	//   0 => 2 #int
	// ]

	// Example: integers - tie for mode
	collection.Dump(collection.Mode([]int{1, 2, 1, 2}))
	// #[]int [
	//   0 => 1 #int
	//   1 => 2 #int
	// ]

	// Example: floats
	collection.Dump(collection.Mode([]float64{1.1, 2.2, 1.1, 3.3}))
	// #[]float64 [
	//   0 => 1.100000 #float64
	// ]

	// Example: integers - empty collection
	collection.Dump(collection.Mode([]int{}))
	// []int(nil)
}
