//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection"

func main() {
	// Mode returns the most frequent numeric value or values in a slice.
	// If multiple values tie for highest frequency, all are returned
	// in first-seen order.

	// Example: integers – single mode
	values := []int{1, 2, 2, 3}
	mode := collection.Mode(values)
	collection.Dump(mode)
	// #[]int [
	//   0 => 2 #int
	// ]

	// Example: integers – tie for mode
	values2 := []int{1, 2, 1, 2}
	mode2 := collection.Mode(values2)
	collection.Dump(mode2)
	// #[]int [
	//   0 => 1 #int
	//   1 => 2 #int
	// ]

	// Example: floats
	values3 := []float64{1.1, 2.2, 1.1, 3.3}
	mode3 := collection.Mode(values3)
	collection.Dump(mode3)
	// #[]float64 [
	//   0 => 1.100000 #float64
	// ]

	// Example: integers - empty collection
	empty := []int{}
	mode4 := collection.Mode(empty)
	collection.Dump(mode4)
	// []int(nil)
}
