//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v4"

func main() {
	// Zip combines this collection with values element-wise into pairs.
	// The resulting length is the smaller of the two inputs.

	// Example: integers and strings
	nums := collection.New([]int{1, 2, 3})
	words := []string{"one", "two"}

	out := nums.Zip(words)
	collection.Dump(out)
	// #[]collection.Pair[int,string] [
	//   0 => #collection.Pair[int,string] {
	//     +First  => 1 #int
	//     +Second => "one" #string
	//   }
	//   1 => #collection.Pair[int,string] {
	//     +First  => 2 #int
	//     +Second => "two" #string
	//   }
	// ]
}
