//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection"

func main() {
	// UniqueBy returns a collection containing the first item for each extracted key.

	// Example: keep the first word of each length
	words := collection.New([]string{"go", "up", "forj", "code"})
	unique := words.UniqueBy(func(word string) int {
		return len(word)
	})
	collection.Dump(unique)
	// #[]string [
	//   0 => "go" #string
	//   1 => "forj" #string
	// ]
}
