//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v4"

func main() {
	// Multiply creates `n` copies of all items in the collection
	// and returns a new collection.

	// Example: integers
	ints := collection.New([]int{1, 2})
	collection.Dump(ints.Multiply(3))
	// #[]int [
	//   0 => 1 #int
	//   1 => 2 #int
	//   2 => 1 #int
	//   3 => 2 #int
	//   4 => 1 #int
	//   5 => 2 #int
	// ]

	// Example: strings
	collection.Dump(collection.New([]string{"a", "b"}).Multiply(2))
	// #[]string [
	//   0 => "a" #string
	//   1 => "b" #string
	//   2 => "a" #string
	//   3 => "b" #string
	// ]

	// Example: structs
	type User struct {
		Name string
	}

	users := collection.New([]User{{Name: "Alice"}, {Name: "Bob"}})
	collection.Dump(users.Multiply(2))
	// #[]main.User [
	//   0 => #main.User {
	//     +Name => "Alice" #string
	//   }
	//   1 => #main.User {
	//     +Name => "Bob" #string
	//   }
	//   2 => #main.User {
	//     +Name => "Alice" #string
	//   }
	//   3 => #main.User {
	//     +Name => "Bob" #string
	//   }
	// ]

	// Example: multiplying by zero or negative returns empty
	collection.Dump(ints.Multiply(0))
	// #[]int [
	// ]
}
