//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v4"

func main() {
	// Intersect returns a new collection containing elements from the second
	// collection that are also present in the first.

	// Example: integers
	a := collection.New([]int{1, 2, 2, 3, 4})
	b := collection.New([]int{2, 4, 4, 5})

	collection.Dump(collection.Intersect(a, b))
	// #[]int [
	//   0 => 2 #int
	//   1 => 4 #int
	//   2 => 4 #int
	// ]

	// Example: strings
	left := collection.New([]string{"apple", "banana", "cherry"})
	right := collection.New([]string{"banana", "date", "cherry", "banana"})

	collection.Dump(collection.Intersect(left, right))
	// #[]string [
	//   0 => "banana" #string
	//   1 => "cherry" #string
	//   2 => "banana" #string
	// ]

	// Example: structs
	type User struct {
		ID   int
		Name string
	}

	groupA := collection.New([]User{
		{ID: 1, Name: "Alice"},
		{ID: 2, Name: "Bob"},
		{ID: 3, Name: "Carol"},
	})

	groupB := collection.New([]User{
		{ID: 2, Name: "Bob"},
		{ID: 3, Name: "Carol"},
		{ID: 4, Name: "Dave"},
	})

	collection.Dump(collection.Intersect(groupA, groupB))
	// #[]main.User [
	//   0 => #main.User {
	//     +ID   => 2 #int
	//     +Name => "Bob" #string
	//   }
	//   1 => #main.User {
	//     +ID   => 3 #int
	//     +Name => "Carol" #string
	//   }
	// ]
}
