//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection"

func main() {
	// Max returns the largest item in a numeric slice.
	// The second return value is false if the slice is empty.

	// Example: integers
	values := []int{3, 1, 2}

	max1, ok1 := collection.Max(values)
	collection.Dump(max1, ok1)
	// 3 #int
	// true #bool

	// Example: floats
	values2 := []float64{1.5, 9.2, 4.4}

	max2, ok2 := collection.Max(values2)
	collection.Dump(max2, ok2)
	// 9.200000 #float64
	// true #bool

	// Example: empty numeric slice
	empty := []int{}

	max3, ok3 := collection.Max(empty)
	collection.Dump(max3, ok3)
	// 0 #int
	// false #bool
}
