version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directories:
      - /
      - /docs
      - /docs/bench
      - /docs/regression
      - /examples
    schedule:
      interval: weekly
    groups:
      shared-dependencies:
        group-by: dependency-name
