version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /docs
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /docs/bench
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /docs/regression
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /examples
    schedule:
      interval: weekly
