//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/collection/v3"
)

func main() {
	// Retain keeps items for which fn returns true in c's existing backing array.

	// Example: keep even integers without allocating another backing array
	values := collection.New([]int{1, 2, 3, 4})
	evens := values.Retain(func(value int) bool { return value%2 == 0 })
	collection.Dump(evens)
	// #[]int [
	//   0 => 2 #int
	//   1 => 4 #int
	// ]
	fmt.Println(values)
	// [2 4 0 0]
}
