//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection"

func main() {
	// Sum returns the sum of all items in a numeric slice.
	// If the slice is empty, Sum returns the zero value of T.

	// Example: integers
	values := []int{1, 2, 3}
	total := collection.Sum(values)
	collection.Dump(total)
	// 6 #int

	// Example: floats
	values2 := []float64{1.5, 2.5}
	total2 := collection.Sum(values2)
	collection.Dump(total2)
	// 4.000000 #float64

	// Example: integers - empty collection
	empty := []int{}
	total3 := collection.Sum(empty)
	collection.Dump(total3)
	// 0 #int
}
