//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v4"

func main() {
	// Sum returns the sum of all items in a numeric slice.
	// If the slice is empty, Sum returns the zero value of T.

	// Example: integers
	collection.Dump(collection.Sum([]int{1, 2, 3}))
	// 6 #int

	// Example: floats
	collection.Dump(collection.Sum([]float64{1.5, 2.5}))
	// 4.000000 #float64

	// Example: integers - empty collection
	collection.Dump(collection.Sum([]int{}))
	// 0 #int
}
