//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/collection"
)

func main() {
	// ToPrettyJSON converts the collection's items into a human-readable,
	// indented JSON string.

	// Example: strings - pretty JSON
	pj1 := collection.New([]string{"a", "b"})
	out1, _ := pj1.ToPrettyJSON()
	fmt.Println(out1)
	// [
	//  "a",
	//  "b"
	// ]
}
