//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v3"

func main() {
	// ToMap reduces this collection into a map using the provided key and value functions.

	// Example: index words by their value
	words := collection.New([]string{"go", "forj"})
	lengths := words.ToMap(
		func(word string) string { return word },
		func(word string) int { return len(word) },
	)
	collection.Dump(lengths)
	// #map[string]int {
	//   forj => 4 #int
	//   go => 2 #int
	// }
}
