//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v4"

func main() {
	// None returns true if fn returns false for every item in the collection.
	// If the collection is empty, None returns true.

	// Example: integers - none even
	collection.Dump(collection.New([]int{1, 3, 5}).None(func(v int) bool { return v%2 == 0 }))
	// true #bool

	// Example: integers - some even
	collection.Dump(collection.New([]int{1, 2, 3}).None(func(v int) bool { return v%2 == 0 }))
	// false #bool

	// Example: empty collection
	collection.Dump(collection.New([]int{}).None(func(v int) bool { return v > 0 }))
	// true #bool
}
