//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v4"

func main() {
	// Dd prints items then terminates execution.
	// Like Laravel's dd(), this is intended for debugging and
	// should not be used in production control flow.

	// Example: strings
	collection.New([]string{"a", "b"}).Dd()
	// #[]string [
	//   0 => "a" #string
	//   1 => "b" #string
	// ]
	// Process finished with the exit code 1
}
