//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v3"

func main() {
	// UniqueComparable returns a new collection with duplicate comparable items removed.
	// The first occurrence of each value is kept, and order is preserved.
	// It uses a map to track seen values, so it has expected linear time and allocates
	// storage for both the map and the result.

	// Example: integers
	collection.Dump(collection.UniqueComparable([]int{1, 2, 2, 3, 4, 4, 5}))
	// #[]int [
	//   0 => 1 #int
	//   1 => 2 #int
	//   2 => 3 #int
	//   3 => 4 #int
	//   4 => 5 #int
	// ]

	// Example: strings
	collection.Dump(collection.UniqueComparable([]string{"A", "a", "B", "B"}))
	// #[]string [
	//   0 => "A" #string
	//   1 => "a" #string
	//   2 => "B" #string
	// ]
}
