//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/collection"
)

func main() {
	// Concat appends values to c, using c's spare capacity when it is available.

	// Example: strings
	c := collection.New([]string{"John Doe"})
	concatenated := c.
		Concat([]string{"Jane Doe"}).
		Concat([]string{"Johnny Doe"})
	collection.Dump(concatenated)

	// #[]string [
	//  0 => "John Doe" #string
	//  1 => "Jane Doe" #string
	//  2 => "Johnny Doe" #string
	// ]

	// Example: spare capacity
	backing := make([]int, 2, 4)
	copy(backing, []int{1, 2})
	values := collection.New(backing)
	values = values.Concat([]int{3, 4})
	fmt.Println(values)
	// [1 2 3 4]
}
