//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v4"

func main() {
	// ZipWith combines this collection with a slice using fn up to the shorter length.

	// Example: add corresponding integers
	left := collection.New([]int{1, 2, 3})
	right := collection.New([]int{10, 20})
	sums := left.ZipWith(right, func(a, b int) int {
		return a + b
	})
	collection.Dump(sums)
	// #[]int [
	//   0 => 11 #int
	//   1 => 22 #int
	// ]
}
