//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v3"

func main() {
	// CountByValue returns the number of occurrences of each distinct item in c.

	// Example: strings
	values := []string{"go", "forj", "go"}
	counts := collection.CountByValue(values)
	collection.Dump(counts)
	// #map[string]int {
	//   forj => 1 #int
	//   go => 2 #int
	// }
}
