//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/collection/v4"
)

func main() {
	// GroupBy partitions this Slice into independent built-in slices keyed by the
	// extracted value.

	// Example: group integers by parity
	numbers := collection.New([]int{1, 2, 3, 4})
	groups := numbers.GroupBy(func(number int) string {
		if number%2 == 0 {
			return "even"
		}
		return "odd"
	})
	collection.Dump(groups["even"], groups["odd"])
	// #[]int [
	//   0 => 2 #int
	//   1 => 4 #int
	// ]
	// #[]int [
	//   0 => 1 #int
	//   1 => 3 #int
	// ]
	fmt.Println(len(groups["even"]))
	// 2
	fmt.Println(groups["odd"][0])
	// 1
	collection.Dump(groups["even"][:1])
	// #[]int [
	//   0 => 2 #int
	// ]
}
