//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v3"

func main() {
	// Dump is a convenience function that calls godump.Dump.

	// Example: integers
	collection.Dump(collection.New([]int{1, 2, 3}))
	// #[]int [
	//   0 => 1 #int
	//   1 => 2 #int
	//   2 => 3 #int
	// ]
}
