//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/collection/v3"
)

func main() {
	// Shuffle shuffles the collection in place and returns the same collection.

	// Example: integers
	c := collection.New([]int{1, 2, 3, 4, 5})
	c.Shuffle()
	fmt.Println(len(c), collection.Sum(c))
	// 5 15

	// Example: strings - chaining
	out2 := collection.New([]string{"a", "b", "c"}).
		Shuffle().
		Concat([]string{"d"})

	fmt.Println(len(out2))
	// 4

	// Example: structs
	type User struct {
		ID int
	}

	users := collection.New([]User{
		{ID: 1},
		{ID: 2},
		{ID: 3},
		{ID: 4},
	})

	users.Shuffle()
	fmt.Println(len(users))
	// 4
}
