//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection"

func main() {
	// Pipe passes this Slice value to fn and returns fn's result.

	// Example: sum a collection
	numbers := collection.New([]int{1, 2, 3})
	total := numbers.Pipe(func(values collection.Slice[int]) int {
		sum := 0
		for _, value := range values {
			sum += value
		}
		return sum
	})
	collection.Dump(total)
	// 6 #int
}
