//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import (
	"github.com/goforj/collection/v4"
	"strings"
)

func main() {
	// Transform applies a same-type transformation in place and returns the same collection.

	// Example: integers
	c := collection.New([]int{1, 2, 3})

	c.Transform(func(v int) int {
		return v * 10
	})

	collection.Dump(c)
	// #[]int [
	//   0 => 10 #int
	//   1 => 20 #int
	//   2 => 30 #int
	// ]

	// Example: strings
	c2 := collection.New([]string{"apple", "banana", "cherry"})

	upper := c2.Transform(func(s string) string {
		return strings.ToUpper(s)
	})

	collection.Dump(upper)
	// #[]string [
	//   0 => "APPLE" #string
	//   1 => "BANANA" #string
	//   2 => "CHERRY" #string
	// ]

	// Example: structs
	type User struct {
		ID   int
		Name string
	}

	users := collection.New([]User{
		{ID: 1, Name: "Alice"},
		{ID: 2, Name: "Bob"},
	})

	updated := users.Transform(func(u User) User {
		u.Name = strings.ToUpper(u.Name)
		return u
	})

	collection.Dump(updated)
	// #[]main.User [
	//   0 => #main.User {
	//     +ID   => 1 #int
	//     +Name => "ALICE" #string
	//   }
	//   1 => #main.User {
	//     +ID   => 2 #int
	//     +Name => "BOB" #string
	//   }
	// ]
}
