//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/collection"
)

func main() {
	// Items returns the backing slice as []T.

	// Example: migration comparison
	values := collection.New([]int{10, 20, 30})
	fmt.Println([]int(values))
	// [10 20 30]
	fmt.Println(values.Items())
	// [10 20 30]
}
