//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection"

func main() {
	// MinBy returns the item whose extracted key is the smallest.

	// Example: shortest string
	words := collection.New([]string{"pear", "fig", "banana"})
	shortest, ok := words.MinBy(func(word string) int {
		return len(word)
	})
	collection.Dump(shortest, ok)
	// "fig" #string
	// true #bool
}
