//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/collection/v3"
)

func main() {
	// Map maps this Slice to a newly allocated Slice with a potentially different
	// element type.

	// Example: map integers to labels
	numbers := collection.New([]int{1, 2, 3, 4})
	labels := numbers.Map(func(number int) string {
		if number%2 == 0 {
			return "even"
		}
		return "odd"
	})
	collection.Dump(labels)
	// #[]string [
	//   0 => "odd" #string
	//   1 => "even" #string
	//   2 => "odd" #string
	//   3 => "even" #string
	// ]
	fmt.Println(numbers[0])
	// 1
}
