//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v3"

func main() {
	// Avg returns the average of the numeric slice values as a float64.
	// If the slice is empty, Avg returns 0.

	// Example: integers
	values := []int{2, 4, 6}
	collection.Dump(collection.Avg(values))
	// 4.000000 #float64

	// Example: float
	values2 := []float64{1.5, 2.5, 3.0}
	collection.Dump(collection.Avg(values2))
	// 2.333333 #float64
}
