//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v4"

func main() {
	// Avg returns the average of the numeric slice values as a float64.
	// If the slice is empty, Avg returns 0.

	// Example: integers
	collection.Dump(collection.Avg([]int{2, 4, 6}))
	// 4.000000 #float64

	// Example: float
	collection.Dump(collection.Avg([]float64{1.5, 2.5, 3.0}))
	// 2.333333 #float64
}
