//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/collection/v3"
)

func main() {
	// New creates a Slice from items and borrows their backing array.

	// Example: native slice operations
	values := collection.New([]int{10, 20, 30})
	fmt.Println(len(values))
	// 3
	fmt.Println(values[1])
	// 20

	total := 0
	for _, value := range values {
		total += value
	}
	fmt.Println(total)
	// 60
}
