//go:build ignore
// +build ignore

// Code generated by docs/gen; DO NOT EDIT.

package main

import "github.com/goforj/collection/v4"

func main() {
	// Difference returns a new collection containing elements from the first collection
	// that are not present in the second. Order follows the first collection, and
	// duplicates are removed.

	// Example: integers
	a := collection.New([]int{1, 2, 2, 3, 4})
	b := collection.New([]int{2, 4})

	collection.Dump(collection.Difference(a, b))
	// #[]int [
	//   0 => 1 #int
	//   1 => 3 #int
	// ]

	// Example: strings
	left := collection.New([]string{"apple", "banana", "cherry"})
	right := collection.New([]string{"banana"})

	collection.Dump(collection.Difference(left, right))
	// #[]string [
	//   0 => "apple" #string
	//   1 => "cherry" #string
	// ]

	// Example: structs
	type User struct {
		ID   int
		Name string
	}

	groupA := collection.New([]User{
		{ID: 1, Name: "Alice"},
		{ID: 2, Name: "Bob"},
		{ID: 3, Name: "Carol"},
	})

	groupB := collection.New([]User{
		{ID: 2, Name: "Bob"},
	})

	collection.Dump(collection.Difference(groupA, groupB))
	// #[]main.User [
	//   0 => #main.User {
	//     +ID   => 1 #int
	//     +Name => "Alice" #string
	//   }
	//   1 => #main.User {
	//     +ID   => 3 #int
	//     +Name => "Carol" #string
	//   }
	// ]
}
